/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DateTime: typeof import('./src/utils/helpers.js').DateTime
  const date: typeof import('./src/utils/helpers.js').date
  const dateAndTime: typeof import('./src/utils/helpers.js').dateAndTime
  const dateTime: typeof import('./src/utils/helpers.js').dateTime
  const formatDate: typeof import('./src/utils/helpers.js').formatDate
  const formatDateTime: typeof import('./src/utils/helpers.js').formatDateTime
  const formatTime: typeof import('./src/utils/helpers.js').formatTime
  const formatTimeAgo: typeof import('./src/utils/helpers.js').formatTimeAgo
  const formatTimeAgoOrHumanizeDate: typeof import('./src/utils/helpers.js').formatTimeAgoOrHumanizeDate
  const formatdate: typeof import('./src/utils/helpers.js').formatdate
  const humanizeDae: typeof import('./src/utils/helpers.js').humanizeDae
  const humanizeDate: typeof import('./src/utils/helpers.js').humanizeDate
  const humanizeDateOrTime: typeof import('./src/utils/helpers.js').humanizeDateOrTime
  const humanizeDateOrTimeAgo: typeof import('./src/utils/helpers.js').humanizeDateOrTimeAgo
  const humanized: typeof import('./src/utils/helpers.js').humanized
  const request: typeof import('./src/utils/request.js').default
  const smallWords: typeof import('./src/utils/helpers.js').smallWords
  const toTitleCase: typeof import('./src/utils/helpers.js').toTitleCase
}
